### ISSUE TITLE
Exception in str2time method

### ISSUE THREAD

**Issue by cmft** [tango-controls/fandango#11] opened 2018-11-26 15:22 UTC
In Fandango 14.1.0,  `str2time`  raises an exception when you do not specified the minutes in the date format:
e.g.
```
from fandango.functional import str2time
str2time('2018-11-20T14')
#Exception: ('PARAMS_ERROR', 'date format cannot be parsed!: 2018-11-20T14')
```
However without the seconds works
```
str2time('2018-11-20T14:00')
```

**Comment by sergirubio** [comment] 2018-11-26 15:32
Well, the problem is the 'T' in the string.

str2time assume's few standard date formats accepted by mysql and posgresql; if you are using your own custom format then you should pass it as argument to the function:

fn.str2time('2018-11-20T14:00', cad='%Y-%m-%dT%H:%M')

**Comment by sergirubio** [comment] 2018-11-26 15:47
I'll close this issue and create a new one relative to supporting ISO-8061 on time conversions
Until then, use the custom format argument

**Closed as completed** 2018-11-26 15:47 UTC

**Comment by cmft** [comment] 2018-11-27 08:00
It is not a custom representation; it follows [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601). And  in somehow you support it cause it works as it is expected : `str2time('2018-11-20T14:00')`


Ok

**Comment by sergirubio** [comment] 2018-11-27 08:39
but  not as default, time2str and str2time are expected to be symetric
I will add fandango.functional.DEFAULT_TIME_FORMAT to manage this symmetry
